name: Update KA hotlist

on:  
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  update:
    environment: secrets
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python update.py
