name: 1.4.0 - Remove old API logs

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # checkout the repository content

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip

      - name: Execute python script # run main.py
        run: python remove.py
        
      - name: Use auto-commit library
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: .[BOT] 1.4.0 - Delete old API logs
          
      - name: Use auto-commit library 2nd try
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: .[BOT] 1.4.0 - Delete old API logs
          
      - name: Use auto-commit library 3rd try
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: .[BOT] 1.4.0 - Delete old API logs
#          push_options: '--force'
#        
#      - name: Purging jsdelivr's cache
#        uses: gacts/purge-jsdelivr-cache@v1
#        with:
#          url: |
#            https://cdn.jsdelivr.net/gh/Infinite-Coder-001/Hotlist-API@main/api.js
